#ifndef __ABOUT_H__
#define __ABOUT_H__

#define mateo "                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                               `---.`                                               \n"
"                                            `-/smmddhyo+:`                                          \n"
"                                         .-+hdmmmmmmNNNNmd+`                                        \n"
"                                        .hmdysooosyyydmmmmmy.                                       \n"
"                                       `hds+////////++oshdmmh-                                      \n"
"                                       sh+///////////////ohmmy                                      \n"
"                                      .h+//::/://///::::://ymm-                                     \n"
"                                      sy///////::::::::::://hmy                                     \n"
"                                     .ms+osyyso/:::+ossoo/:/hmd`                                    \n"
"                                     :moo+//+oo+:::/++/::/+/ymm+                                    \n"
"                                     -m++oyhdyyo/:/oyyhso/:/smNs                                    \n"
"                                     /h///++ooo+/::/+++//:::+mm:                                    \n"
"                                     :s//://////::::::::::::/ho-                                    \n"
"                                      ///:::/+++/:/:::::--:::+:`                                    \n"
"                                      ://::://++////:::--::::/-                                     \n"
"                                      ./////////::::::---:::::`                                     \n"
"                                       .////++o+++++//:::::-``                                      \n"
"                                        -///////+//::::::::                                         \n"
"                                         -+++//////:::::::-                                         \n"
"                                          ++++/:/::::///::.                                         \n"
"                                         `//++++++///:::::.                                         \n"
"                                        :+////////:::::-:::-                                        \n"
"                                      .ym:.-::://::::::-.`:mo`                                      \n"
"                                   `-odmm/....-::::/:-````smmhs/-`                                  \n"
"                               .:oymmmmmms.....-oy/.`````-dmmmNNmmy+:.`                             \n"
"                         `.:+sdmmNNNNmmmmy:...-dmmd:````.smmmmmNNNNNmmdy+:-`                        \n"
"                     `:ohdmmNNNNNNNNNmmmmh:-..smmmmy```./hmmmmmNNNNNNNmmmmddy+`                     \n"
"                     ymNNNNNNNNNNNNNNmmmmd--.-ommmm+:`.-/mmmmmmNNNmNNNNmmmmmmmo                     \n"
"                    -mNNmmmmmmNNNNNNNmmmmm/-../mmmm/:..:ommmmmmNmmmmNNNNmmmmmmd-                    \n"
"                    smmNmmmmmmNNNNNNNmmmmmo.-.smmmmy:-./hmmmmmmmmmmmNNNmmmmmmmmy                    \n"
"                   .mmmNmmmmmmmmmmNNNmmmmmy.--hmmmmd:--+mmmmmmmmmmmmNNmmmmmmmmmd:                   \n"
"                   /mmmmNmmmmmmmmmmmNmmmmmd-.-dmmmmm/:-ymmmmmmmmmmmmmmmmmmmmmmmdy                   \n"
"                   ymmmmNmmmmmmmmmmmNmmmmmm:.-mmmmmm+::dmmmmmmmmmmmmmmmmmmNmmmmmd-                  \n"
"                  `mmmmmNNmmmmmmmmmmmNmmmmm+.:mmmmmmo/+mmmmmmmmmmmmmmmmmmmmmmmmmd+                  \n"
"                  /mmmmmNNmmmmmmmmmmmNmmmmmy.-mmmmmms/ymmmmmmmmmmmmmmmmmmNmmmmmmmh                  \n"
"                  ymmmmmNNNmmmmmmmmmmmmmmmmd--mmmmmmh/mmmmmmmmmmmmmmmmmmmmmNmmmmmd.                 \n"
"                  dmmmmmNNNmmmmmmmmmmmNmmmmm/-mmmmmmmymmmmmmmmmmmmmmmmmmmNNmmmmmmm:                 \n"
"                 .mmNNNNNNNNmmmmmmmmmmmmmmmms-mmmmmmNmmmmmmmmmmmmmmmmmmmNNNmmNmmmm/                 \n"
"                 :mmmNNNNNNNmmmmmmmmmmmNmmmmd-dNmmmNNmmmmmmmmmmmmmmmmmmmNNNNNmmmmm/                 \n"
"                 ommmmNNNNNMNmmmmmmmmmmmNmmmm+hNNmmNNmmmmmmmmmmmmmmmmmmNNNNmmmmmmm+                 \n"
"                 ymmmmNNNNNMNmmmNNmmmmmmNmmmmsyNNNNNNmmmmmmmmmmmmmmmmmmNNNmmmmmmmmo                 \n"
"                 dmmmmNNNNNNMmmmNNNmmmmmNNmmmdsNNNNNmmmmmmmmmmmmmmmmmmmNNNmmmNmmmds                 \n"
"                 mmmmmNNNNNNMNmmNNNmmmmmNNNmmmhNNNNNmmmmmmmmmmmmmmmmmmNNNNmmmNmmmds                 \n"
"                `mmmmmmNNNNNNNmmNNNNmmmmmNNmmmmNNNNNmmmmmmmmmmmmmmmmmmMNNmmmmNNNmds                 \n"
"                 mmmmmmmNNNNNMNNNNNNmmmmmNNNmmmNNNNmmNmmmmmmmmmmmmmmmNMNNmmmNNNNmds                 \n"
"                 dmmmmmNNNNNNMNNNNNNmmmmmmNNNmmNNNNmNmmmmmmmmmmmmmmmmNMNNmNNNNNmdds                 \n"
"                 dmNNNNNNNNNNNNNNNNNNmmmmmNNNmmNMNmmNmmmmmmmmmmmmmmmNMNNNNNNNNmmmds                 \n"
"                 hNNNNNNNNNNNMNNNNNNNNmmmmmNNNmNMNmmmmmmmmmmmmmmmmmmNMNNNNNNNmmddds                 \n"

#define viti "                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                       ````````````                                                 \n"
"                                    `-+ssosyyyyyyyso/:--.`..`                                       \n"
"                                  `/yhdddddddddddddddhhysssss+:.`                                   \n"
"                                `/hdddddddddddddddddddddhhhyyyys+:`                                 \n"
"                              .ohddddddddddddddddddddddddddddddddho.                                \n"
"                             `ydddddddddddddddddddddddddddddddddddhy`                               \n"
"                             /dddddddddddddddddddddddhhddddddddddddh:                               \n"
"                             +dddddddddddddddddddddddhdddddddhddhdhs:                               \n"
"                             oddddddddddddddddddddddyysyyyhhhhyhyyo-                                \n"
"                             yddddddddddddddddddddhhsoo+++++oo++++-                                 \n"
"                             hddddddddddddhhhyyyyysoo+++//////////-                                 \n"
"                             yddddddddddddhyyssssooo+++///////////:                                 \n"
"                             sddddddddddddhhysssso+++++///////////:`                                \n"
"                             /hhhdddddddddhyyysssoo++++++/////////:.                                \n"
"                            .syyssyhhddddhyyyyysssssoossyss++/////::`                               \n"
"                            /yysyyooyhhhhyyyyyyyyyyyyssyyyhys+/+oo+/.                               \n"
"                            /yssyhyyyhhhyyssssssyhhyhhoyyyhys//yhys-                                \n"
"                            -sossyhsyhhyyyssoo++osyysssssyyyo//sy+:`                                \n"
"                             /sssyhyyhhhhyysso++++++oooosssss+/++:.                                 \n"
"                              :ssoosyhhhhhyysso+++++++++osssso///:.                                 \n"
"                               shyyyhhhhhhyyssooo+++++++ossyso+//-`                                 \n"
"                               oddddhhhhhhyysssooo++++++yyysss++/-                                  \n"
"                               odddhhhhhhhyyyssoooo++//+syyyyys+:`                                  \n"
"                              `ydhhhhhhhhhyyyssssooo+++++osso+/:.                                   \n"
"                             .ohhhhhhhhhhhhyyyyssssooooooooo++/:.                                   \n"
"                           ./syyhyyyyhhhhhhhyyyyysssoosyyysss+/:                                    \n"
"                       `.-/+ssssyyyssyyhhhhhhhyyyysssssssooo+/-`                                    \n"
"                     ./shdhysooooyysssssyhhhhhhhyysssssoo+++/:.                                     \n"
"                  `-ohdddddddyo+ooyssooossyyhhhhhyyssooo++//:-                                      \n"
"               `-ohdddddddddddds+osysoooooossyyhhhhyysoo+++/-`                                      \n"
"            `-ohddddddddddddddddhoosso++++ooossssysso+:::--.                                        \n"
"          .+hdddddddddddddddddddddysso+++++++oooooo/:`                                              \n"
"        .odddddddddddddddddddddddddhsoo+++++++++++:.                                                \n"
"        :ddddddddddddddddddddddddddddhs++++//++/:`                                                  \n"
"         -yddddddddddddddddddddddddddddhs+/////+`                                                   \n"
"          `+ddddddddddddddddddddddddddddddyo+ohh+                                                   \n"
"            -sddddddddddddddddddddddddddddddhyddh:                                                  \n"
"             `:yddddddddddddddddddddddddddddhyhdhs`                                                 \n"
"               `:sddddddddddddddddddddddddddhhyhdh:                                                 \n"
"                  -ohdddddddddddddddddddddddhhhhdhs                                                 \n"
"                    `:shdddddddddddddddddddddhdhhhh.                                                \n"
"                       .:ohddddddddddddddddddhdhhhh/                                                \n"
"                          `-/shddddddddddddddhddhdh+                                                \n"
"                               .:+shddddddddddddhdhy                                                \n"
"                                    `.-/+ossyhhdhhyh.                                               \n"

#define kako "                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                  ./++soo+::-`                                      \n"
"                                            `:/+yddmmmNNNNNmmds+.                                   \n"
"                                         -/sdmmNNNmmmmmmmNNNmmmmdy+.                                \n"
"                                      `:ymNNmNNNNNNNmdmmmmNmmmNNNNNdy/`                             \n"
"                                    -sdNNNNNNNmdddmmmmmmmmmmmmNNNNNNmmy`                            \n"
"                                  `omNNNNNNNNdo++oyydmmNNNNNNNNNNNNNNmm/                            \n"
"                                 `hNNmNNNNmmh+/:://+oyhdmmmmmNNNNNNNNmmd.                           \n"
"                                `yNNNmNmmmds///::::--:+oshddddmmmmNmNmmmy`                          \n"
"                                /NNMNNNNmhsssyyyo/:---:+oyhdddddddmNmmmmmy                          \n"
"                                yNMMMNmyyso+//+ooo/:-:/ooo+++osyssdNNmNmmN:                         \n"
"                               .mNMMMNhoooo++/+++o+::/++++/://++oohmmmNmmm/                         \n"
"                               oNNMMMNy++syyhyso+++:://+ooyhhsso++ymNNNmmm/                         \n"
"                               /NNMMMmo///++++//++/--//+//++ooo+/+hNNNNNmN/                         \n"
"                               /NNNNNmo//::::::++ss//oo//::::::://ydmNNNNm.                         \n"
"                                +dNmdd+//::::::osssoosso/:---::::/sdNNNNy-                          \n"
"                                 ./syho+//::::////:::://::----:://ymNNNy                            \n"
"                                  `/+yo+///://+++++++///::::::://oymhNN:                            \n"
"                                   //yo++//:/oo++/////++++:::://+ssssm+                             \n"
"                                   -+ss+++//////:::::::://::://+oso/s-                              \n"
"                                    -+so++++///::-----:::/:////ooo++-                               \n"
"                                     `+soo+++//:------::////++oos+/.                                \n"
"                                      `sysoo+//::----:::///+ooso/.                                  \n"
"                                       oyyyssoo+++//+//++oossyo-                                    \n"
"                                       oyyyssssssoossssssyyyyy`                                     \n"
"                                       ssssssssssossssssssyyy+                                      \n"
"                                      `soosssoooooooooosssooo.                                      \n"
"                                      .s+++osooo+++oooooo///+`                                      \n"
"                                      :o+///+++/////++//:://+                                       \n"
"                                     `oo+//::::::::::::::://+                                       \n"
"                                  `.:+oo+/:::::---:----::::/+/`                                     \n"
"                             `--+yhoo+++/::----:::------:::////---                                  \n"
"                ``..---:/+osydmmNNs+/++++:----------.---:::::::/omho:`                              \n"
"            .:shdddmmmmNNNNNNNNNNd+++///+:-....----..----:::--//hNNNmdo-`                           \n"
"         ./ydNNNNNNNNNNNNNNNNNNNNy++++/:/:-.....--..------::://hNNNNNNNmhs:..-..``                  \n"
"       .odNNNNNNNNNNNNNNNNNNNNNNNy+/////::-....---..----::///odNNNNNNNNNNNNmmmmdhhy+.               \n"
"     .smNNNNNNNNNNNNNNNNNNNNNNNNNd/::::::::-----::--::::::/ohNNNNNNNNNNNNNNNNNNNNNNNd+.             \n"
"    :dNNNNNNNNNNNNNNNNNNNNNNNNNNNNy::---....---:--------/sdNNNNNNNNNNNNNNNNNNNNNNNNNNNd+-`          \n"
"  `sNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmo---.......--------:omNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmy/`       \n"
" -dNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmo----..-.-------:odNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNd/`     \n"
"/mNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNy------------:smNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNh-    \n"
"NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNd+--------:smNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNm+   \n"
"NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNdysoooydmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmy` \n"
"NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNh.\n"
"NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmdhyyyyyhdmNd\n"
"NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmhyo/:::---:::/sh\n"
"NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmds+/::::------::::/\n"
"oyhdmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNms+/:::::::---:::::::\n"
"---:/+osyhdmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNms+//::::::::--:::::::\n"

#endif